# {{projectName}}

Generated by `create-ai-app` with the `{{template}}` template.

## Scripts

```bash
pnpm install
pnpm dev
pnpm lint
pnpm typecheck
pnpm test
pnpm build
```

## AI Coding Rules

- `AGENTS.md`
- `CLAUDE.md`
- `.github/copilot-instructions.md`
- `docs/ai-coding-guidelines.md`
- `docs/workflows/*`

## Architecture

```txt
app → pages → features → shared
```

Do not introduce reverse dependencies.
