# Architecture

This project was generated by `create-ai-app` using the `{{template}}` template.

## Dependency Direction

```txt
app → pages → features → shared
```

## Directory Responsibilities

- `src/app`: application bootstrap, providers, routes.
- `src/pages`: page composition.
- `src/features`: business features.
- `src/shared`: reusable infrastructure and utilities.
- `src/styles`: global styles.

## Rules

- `shared` must not import from `features`, `pages`, or `app`.
- `features` must not import from `pages` or `app`.
- UI-only components must not call APIs directly.
- Business logic should be placed in services and covered by unit tests.
