import type { AiRuleSet } from "../types.js";

export function renderAgentsMd(rules: AiRuleSet): string {
  const serverStateLine = rules.stack.serverState ? `- Server state: ${rules.stack.serverState}` : "";

  return `# AGENTS.md

## Project Overview

This project is generated by create-ai-app.

- Project name: ${rules.project.projectName}
- Framework: ${rules.project.framework}
- Package manager: ${rules.project.packageManager}

## Setup Commands

- Install dependencies: \`${rules.project.packageManager} install\`
- Start dev server: \`${rules.project.packageManager} dev\`
- Run lint: \`${rules.project.packageManager} lint\`
- Run typecheck: \`${rules.project.packageManager} typecheck\`
- Run tests: \`${rules.project.packageManager} test\`
- Build: \`${rules.project.packageManager} build\`

## Tech Stack

- Build tool: ${rules.stack.buildTool}
- Language: ${rules.stack.language}
- Styling: ${rules.stack.styling}
- HTTP client: ${rules.stack.httpClient}
- State manager: ${rules.stack.stateManager}
- Testing: ${rules.stack.testing}
${serverStateLine}

## Architecture

Follow layer-based architecture.

Allowed dependency direction:

\`\`\`txt
${rules.architecture.dependencyDirection.join(" → ")}
\`\`\`

Forbidden dependencies:

${rules.architecture.forbiddenDependencies.map((item) => `- ${item}`).join("\n")}

## Code Style

- Use TypeScript strict mode.
- Prefer named exports.
- Keep functions under ${rules.codeStyle.maxFunctionLines} lines when practical.
- Follow SOLID principles.
- ${rules.codeStyle.commentPolicy}
- Prefer guard clauses over deeply nested conditionals.
- Do not add broad file header comments unless the file contains important architectural context.

## Component Rules

- Separate container and presentational components when data fetching or complex state is involved.
- UI-only components must not call APIs directly.
- Props must be explicit and typed.
- Extract reusable stateful logic into hooks or composables.

## State Management

- ${rules.state.localStatePolicy}
- ${rules.state.globalStatePolicy}
- ${rules.state.serverStatePolicy}
- Do not store server response caches in global client stores.

## Data Fetching

- Use Axios for HTTP transport.
- Normalize API errors in \`shared/api\`.
- Always handle loading, error, empty, and success states.
- Do not expose raw backend errors directly to users.

## Testing

- Business logic implemented as functions must have unit tests.
- API error normalization must have tests.
- Non-trivial hooks or composables should have tests.

## Security

- Do not expose secrets.
- Do not read or modify \`.env\` files unless explicitly requested.
- Sanitize user-generated HTML.
- Avoid dangerous HTML APIs unless explicitly justified.

## Performance

- Use lazy loading for route-level code splitting.
- Do not use memoization blindly.
- Explain performance optimizations when adding them.

## Git Commit Rules

Use Conventional Commit style:

${rules.git.allowedTypes.map((type) => `- ${type}:`).join("\n")}

## Forbidden Changes

Do not modify files listed in \`docs/forbidden-files.md\` unless explicitly requested.

## Validation

After code changes, run:

- \`${rules.project.packageManager} lint\`
- \`${rules.project.packageManager} typecheck\`
- \`${rules.project.packageManager} test\`
- \`${rules.project.packageManager} build\`
`;
}
